name: deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 'v18.13.0'
      - uses: actions/setup-node@v3
        with:
          node-version: 'v18.13.0'
      - uses: pnpm/action-setup@v2
        with: 
          version: 8    
      - run: pnpm install
      - run: pnpm run build-cli
      - run: pnpm run build-unplugin
      - run: pnpm run build
      - run: pnpm run build-site
      #- run: npm run test
      - uses: actions/upload-artifact@v3
        with:
          path: ./packages/docs/.vitepress/dist

      - name: Run test cases
        run: pnpm run coverage

      - name: Upload coverage to Codecov  
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./packages/erabbit/coverage

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref=='refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          node-version: 'v18.13.0'
          path: ./packages/docs/.vitepress/dist
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/.vitepress/dist/artifact
